name: "Make Fnnas"
author: "https://github.com/ophub/fnnas"
description: "Support Amlogic, Rockchip and Allwinner boxes."
inputs:
  mode:
    description: "Select script."
    required: false
    default: "ophub"
  fnnas_path:
    description: "Set fnnas arm64 file path."
    required: false
    default: ""
  fnnas_board:
    description: "Select device board."
    required: false
    default: "all"
  kernel_repo:
    description: "Select kernel repository."
    required: false
    default: "ophub/kernel"
  kernel_usage:
    description: "Set the tags of the stable kernel."
    required: false
    default: "stable"
  fnnas_kernel:
    description: "Select kernel version."
    required: false
    default: "6.1.y_6.12.y"
  auto_kernel:
    description: "Auto use the latest kernel."
    required: false
    default: "true"
  fnnas_size:
    description: "Set the rootfs size(Unit: MiB)."
    required: false
    default: ""
  builder_name:
    description: "Set fnnas builder signature."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cd ${{ github.action_path }}
        echo -e "ophub package actions path: [ ${PWD} ]"

        fnnas_filename="${{ inputs.fnnas_path }}"
        fnnas_savefile="${fnnas_filename##*/}"
        fnnas_savepath="fnnas-arm64"
        fnnas_outpath="fnnas/out"
        echo -e "Get fnnas file input parameters: [ ${fnnas_filename} ]"
        [[ -z "${fnnas_filename}" ]] && echo -e "The [ fnnas_path ] variable must be specified." && exit 1
        [[ -d "${fnnas_savepath}" ]] || mkdir -p ${fnnas_savepath}
        [[ -d "${fnnas_outpath}" ]] || mkdir -p ${fnnas_outpath}

        if [[ "${fnnas_filename}" =~ ^http ]]; then
            echo -e "Download file: [ ${fnnas_filename} ]"
            curl -fsSL "${fnnas_filename}" -o "${fnnas_savepath}/${fnnas_savefile}"
        else
            if [[ -z "$(ls ${fnnas_savepath}/${fnnas_savefile} 2>/dev/null)" ]]; then
                echo -e "Copy fnnas rootfs file: [ ${fnnas_filename} ]"
                if [[ "${fnnas_filename}" =~ ^/ ]]; then
                    cp -vf ${fnnas_filename} ${fnnas_savepath}/ || true
                else
                    cp -vf ${{ github.workspace }}/${fnnas_filename} ${fnnas_savepath}/ || true
                fi
            else
                echo -e "The [ ${fnnas_savepath}/${fnnas_savefile} ] file already exists, skipping."
            fi
        fi
        sync
        echo -e "About the [ ${fnnas_savepath} ] directory: \n$(ls -lh ${fnnas_savepath} 2>/dev/null)"

        cd ${fnnas_savepath}
        echo -e "Check the fnnas file format..."
        down_file="$(ls -l *.img* 2>/dev/null | grep "^-" | awk '{print $9}' | sort -u | head -n 1)"
        if [[ -n "${down_file}" ]]; then
            echo -e "Selected fnnas file: [ ${down_file} ]"
        else
            echo -e "The fnnas file is invalid."
            exit 1
        fi
        [[ "${down_file:0-7}" == ".img.gz" ]] && gzip -df ${down_file} 2>/dev/null && sync
        [[ "${down_file:0-7}" == ".img.xz" ]] && xz -d ${down_file} 2>/dev/null && sync
        [[ "${down_file:0-4}" == ".zip" ]] && unzip -o ${down_file} 2>/dev/null && sync
        echo -e "fnnas file: \n$(ls -lh *.img 2>/dev/null)"

        cd ${{ github.action_path }}
        echo -e "Start to make fnnas..."
        make_command=""
        [[ -n "${{ inputs.fnnas_board }}" ]] && make_command="${make_command} -b ${{ inputs.fnnas_board }}"
        [[ -n "${{ inputs.kernel_repo }}" ]] && make_command="${make_command} -r ${{ inputs.kernel_repo }}"
        [[ -n "${{ inputs.kernel_usage }}" ]] && make_command="${make_command} -u ${{ inputs.kernel_usage }}"
        [[ -n "${{ inputs.fnnas_kernel }}" ]] && make_command="${make_command} -k ${{ inputs.fnnas_kernel }}"
        [[ -n "${{ inputs.auto_kernel }}" ]] && make_command="${make_command} -a ${{ inputs.auto_kernel }}"
        [[ -n "${{ inputs.fnnas_size }}" ]] && make_command="${make_command} -s ${{ inputs.fnnas_size }}"
        [[ -n "${{ inputs.builder_name }}" ]] && make_command="${make_command} -n ${{ inputs.builder_name }}"
        read -r -a make_args <<< "${make_command}"
        sudo ./renas "${make_args[@]}"

        cd ${{ github.action_path }}
        echo -e "Output environment variables."
        echo "PACKAGED_OUTPUTPATH=${PWD}/${fnnas_outpath}" >> ${GITHUB_ENV}
        echo "PACKAGED_OUTPUTDATE=$(date +"%m.%d.%H%M")" >> ${GITHUB_ENV}
        echo "PACKAGED_STATUS=success" >> ${GITHUB_ENV}
        echo -e "PACKAGED_OUTPUTPATH: ${PWD}/${fnnas_outpath}"
        echo -e "PACKAGED_OUTPUTDATE: $(date +"%m.%d.%H%M")"
        echo -e "PACKAGED_STATUS: success"
        echo -e "PACKAGED_OUTPUTPATH files list: \n$(ls -lh ${PWD}/${fnnas_outpath}/ 2>/dev/null)"

branding:
  icon: "terminal"
  color: "gray-dark"
